apiVersion: v1
kind: Service
metadata:
  name: {{ template "laravel.name" . }}-svc
  labels:
    app: {{ template "laravel.name" . }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ template "laravel.name" . }}
    tier: {{ template "laravel.tier" . }}
  type: LoadBalancer
