apiVersion: v1
kind: Service
metadata:
  name: {{ template "laravel.name" . }}-{{ template "mysql.name" . }}
  labels:
    app: {{ template "laravel.name" . }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ template "laravel.name" . }}
    tier: {{ template "mysql.name" . }}
  clusterIP: None
