apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mysql.name" . }}-pv-claim
  labels:
    app: {{ template "laravel.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi