version: '3'
services:
  laravel:
    build: ./laravel-application/
    restart: unless-stopped
    container_name: laravel-application
    volumes:
      - ./laravel-application/:/var/www/laravel-application
    links:
      - db

  nginx:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    volumes:
      - ./laravel-application/:/var/www/laravel-application
      - ./config/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - laravel
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    
