version: '3.7'
services:
  laravel:
    image: jesusgr4/images-repository:laravel-app
    build:
      context: ./laravel-application/
      dockerfile: Dockerfile
      args:
        - VENDOR_DIR=$ENV_VENDOR
    command: bash -c "cd /var/www/laravel-application && php artisan key:generate && composer dump-autoload && php-fpm"
    restart: always
    container_name: laravel-application
    logging:
      driver: "json-file"
    volumes:
      - ./laravel-application/:/var/www/laravel-application
      - vendor:$ENV_VENDOR
    links:
      - db

  nginx:
    image: nginx:alpine
    container_name: server
    restart: always
    volumes:
      - ./laravel-application/:/var/www/laravel-application
      - ./config/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
      - type: volume
        source: vendor
        target: $ENV_VENDOR
        volume:
          nocopy: true
    depends_on:
      - laravel
    ports:
      - "$HTTP_PORT:80"
    links:
      - laravel
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "$DB_PORT:3306"
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

volumes:
  vendor:
    
