version: '3.7'
services:
  laravel:
    image: jesusgr4/laravel-repository:laravel-keepcoding
    build:
      context: ./nginx/laravel-application/
      dockerfile: Dockerfile
      args:
        - VENDOR_DIR=$ENV_VENDOR
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - ENCRYPTED_KEY=$ENCRYPTED_KEY
      - ENVIRONMENT=$ENVIRONMENT
      - DEBUG_MODE=$DEBUG_MODE
    restart: unless-stopped
    container_name: laravel-application
    logging:
      driver: "json-file"
    volumes:
      - ./nginx/laravel-application:/var/www/html
    links:
      - db

  nginx:
    image: jesusgr4/laravel-repository:nginx-keepcoding
    build:
      context: ./nginx/
      dockerfile: Dockerfile
      args:
        - VENDOR_DIR=$ENV_VENDOR
    container_name: server
    restart: unless-stopped
    volumes:
      - ./nginx/laravel-application:/var/www/html
    depends_on:
      - laravel
    ports:
      - "$HTTP_PORT:80"
    links:
      - laravel
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
